name: test
on: 
  workflow_dispatch:
  pull_request:
    types: [ edited, ready_for_review, assigned, unassigned, opened, reopened, synchronize ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: compile & run
        run: |
          # downloads age-keygen
          wget https://github.com/FiloSottile/age/releases/download/v1.0.0/age-v1.0.0-linux-amd64.tar.gz
          tar xf age-v1.0.0-linux-amd64.tar.gz
          sudo mv age/age-keygen /usr/local/bin

          # downloads go
          make install-scripts
          sudo ./install-go

          # builds source
          make
          ./lofi

          # runs integration test
          ./.github/workflows/test.sh
