name: test
on: 
  pull_request:
    types: [ edited, ready_for_review, assigned, unassigned, opened, reopened, synchronize ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: compile & run
        run: |
          # setup
          make install-scripts
          sudo ./install-go
          ./test.sh
